apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  mongo-root-username: {{ .Values.auth.rootUser | b64enc | quote }}
  mongo-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
