apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express-app
          image: aseerkt/k8-express:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8500
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: mongo-url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  selector:
    app: express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8500
      nodePort: 30000
